---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- ../../bases/v3.0.6
- app-projects.yaml

patches:
- patch: |-
    - op: add
      path: /data/kustomize.buildOptions
      value: --enable-helm
  target:
    version: v1
    kind: ConfigMap
    name: argocd-cm